# Generated by Django 4.1.4 on 2024-04-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
