# Generated by Django 4.1.4 on 2024-04-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_id_profile_created_at_profile_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="coupon",
        ),
    ]
