# Generated by Django 4.1.4 on 2024-04-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
