# Generated by Django 4.1.4 on 2024-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_cart_coupon"),
        ("products", "0012_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
