# Generated by Django 4.1.4 on 2024-04-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
