# Generated by Django 4.1.4 on 2024-04-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="minimun_amount",
            new_name="minimum_amount",
        ),
    ]
